name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Deploy to the server using sshpass
      - name: Deploy to Server
        env:
          SSHPASS: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -e ssh -o StrictHostKeyChecking=no root@79.127.70.82 <<EOF
            cd /var/www/sitrip.com/backend
            git stash
            git pull origin main
            php artisan migrate
            php artisan config:clear
            php artisan route:clear
            php artisan cache:clear
            composer install
            exit
          EOF
